名字：名称：安卓持续集成



: [    分支: [ "master" ]"master" ]
  拉取请求:
    分支: [    分支: [ "master" ]"master" ]

工作:
  构建:

    runs-on:     运行于：ubuntu-latest

    步骤:
    - 使用：     - 使用：actions/checkout@v4
    - 名称:     - 名称: 设置 JDK 11
      uses:             用途：actions/setup-java@v4
      与：
        java-version: '11'
        分布：' temurin '
        缓存： 缓存：gradle

    - name:     - name: 授予 gradlew 执行权限
      run:       运行：chmod +x gradlew
    - 名称：     - 名称：使用 Gradle 构建
      运行:       运行：./gradlew build
